# Generated by Django 3.2.6 on 2021-09-16 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('pan', models.CharField(max_length=30)),
                ('kardartaname', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=6)),
                ('duration', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Khariddata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khariddate', models.CharField(max_length=20)),
                ('kharidbijan', models.CharField(max_length=20)),
                ('aapurtiname', models.CharField(max_length=200)),
                ('aapurtilekha', models.CharField(max_length=20)),
                ('pauthariname', models.CharField(max_length=200)),
                ('pauthariquantity', models.IntegerField()),
                ('totalbuyprice', models.IntegerField()),
                ('pautharitotalprice', models.IntegerField()),
                ('buyprice', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('taxbuyprice', models.IntegerField()),
                ('pauthariprice', models.IntegerField()),
                ('pautharitax', models.IntegerField()),
                ('pautharitaxprice', models.IntegerField()),
                ('pujigatprice', models.IntegerField()),
                ('pujigattax', models.IntegerField()),
                ('pujigattaxprice', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='posts')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateof', models.CharField(max_length=20, unique=True)),
                ('bijan', models.CharField(max_length=30)),
                ('kharidname', models.CharField(max_length=200)),
                ('kharidlekha', models.CharField(max_length=30)),
                ('sewaname', models.CharField(max_length=200)),
                ('totalsell', models.IntegerField()),
                ('sthaniyakar', models.IntegerField()),
                ('price', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('sewaprice', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('nikasipatra', models.CharField(max_length=30)),
                ('nikasidate', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='post')),
            ],
        ),
    ]
