# Generated by Django 3.2.6 on 2021-09-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='pariman',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
